version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skej
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    depends_on:
      - db
    container_name: flask
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgres://postgres:postgres@db:5432/skej
    volumes:
      - ./migrations:/usr/src/app/migrations
    expose:
      - "3031"

  nginx:
    build: ./nginx
    depends_on:
      - flask
    container_name: nginx
    ports:
      - "80:80"


