"""empty message

Revision ID: 6fecb3f04e7b
Revises: 79586432f7f2
Create Date: 2020-07-08 21:31:27.716991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fecb3f04e7b'
down_revision = '79586432f7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadlines', 'status')
    # ### end Alembic commands ###
